def show_menu():
    print("=" * 40)
    print(" Ada Market Lab")
    print("=" * 40)
    print("1. 新增交易")
    print("2. 查看统计")
    print("3. 查看资金曲线")
    print("4. 仓位/风险计算器")
    print("5. 回测系统")
    print("6. 策略对比系统")
    print("10. 退出")